// OVERALL BASIC  LAYOUT

// CALL WEATHERMAP USING AJAX

//READ DATA BEING RETURNED AND FIND WHAT TO USE

//RETRIEVE COORDINATES FROM GOECODER IN MAPBOX.JS

//USE COORDINATES IN AJAX TO FIND DATA AND THEN SEND THE DATA TO A FUNCTION IN DOM-WEATHER-LOADER.JS